apiVersion: "v1"
kind: "List"
items:
  -
    apiVersion: "v1"
    kind: "Service"
    metadata:
      labels:
        component: "elasticsearch"
      name: "elasticsearch"
    spec:
      ports:
      -
        port: 9200
        targetPort: 9200
      selector:
        component: "elasticsearch"
  -
    apiVersion: "v1"
    kind: "ReplicationController"
    metadata:
      labels:
        component: "elasticsearch"
      name: "elasticsearch"
    spec:
      replicas: 1
      selector:
        component: "elasticsearch"
      template:
        metadata:
          labels:
            component: "elasticsearch"
        spec:
          containers:
            -
              image: "library/elasticsearch:1.5.2"
              name: "elasticsearch"
              ports:
              -
                containerPort: 9200
                name: "http"