apiVersion: "v1"
kind: "List"
items:
  -
    apiVersion: "v1"
    kind: "Service"
    metadata:
      labels:
        provider: "million12"
        component: "zabbix-server"
      name: "zabbix-server"
    spec:
      ports:
        -
          port: 80
          targetPort: 80
        -
          port: 10051
          targetPort: 10051
      selector:
        provider: "million12"
        component: "zabbix-server"
  -
    apiVersion: "v1"
    kind: "ReplicationController"
    metadata:
      labels:
        provider: "million12"
        component: "zabbix-server"
      name: "zabbix-server"
    spec:
      replicas: 1
      selector:
        provider: "million12"
        component: "zabbix-server"
      template:
        metadata:
          labels:
            provider: "million12"
            component: "zabbix-server"
        spec:
          containers:
            -
              env:
                -
                  name: "DB_ADDRESS"
                  value: "zabbix-mariadb"
                -
                  name: "DB_USER"
                  value: "username"
                -
                  name: "DB_PASS"
                  value: "my_password"
              image: "million12/zabbix-server"
              name: "zabbix-server"
              ports:
                -
                  containerPort: 80
                -
                  containerPort: 10051